# Generated by Django 3.2.6 on 2021-11-19 10:12

import django.contrib.postgres.indexes
from django.db import migrations, models

BATCH_SIZE = 10000


def set_search_document(apps, schema_editor):
    Order = apps.get_model("order", "Order")

    orders = []
    for order in Order.objects.iterator():
        order.search_document = prepare_search_document_value(order)
        orders.append(order)

    Order.objects.bulk_update(orders, ["search_document"], batch_size=BATCH_SIZE)


def prepare_search_document_value(order):
    search_document = str(order.id)

    user_data = order.user_email
    if user := order.user:
        user_data += f"{user.first_name}{user.last_name}{user.email}"
    search_document += user_data

    search_document += "".join(order.payments.values_list("psp_reference", flat=True))
    search_document += "".join(
        [
            "".join(data)
            for data in order.discounts.values_list("name", "translated_name")
        ]
    )

    search_document += "".join(order.lines.values_list("product_sku", flat=True))

    for address_field in ["billing_address", "shipping_address"]:
        if address := getattr(order, address_field):
            search_document += (
                f"{address.first_name}{address.last_name}"
                f"{address.street_address_1}{address.street_address_2}"
                f"{address.city}{address.postal_code}{address.country}{address.phone}"
            )

    search_document = search_document.replace(" ", "").lower()

    return search_document


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0120_orderline_optional_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="search_document",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(set_search_document, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="order",
            name="order_order_user_em_bda05b_gin",
        ),
        migrations.AddIndex(
            model_name="order",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["user_email", "search_document"],
                name="order_search_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
